# AUTOGENERATED BY THE GRADLE SCRIPT. EDITS WILL BE OVERWRITTEN.
# encoding: utf-8
require "logstash/filters/base"
require "logstash/namespace"
require "logstash-filter-ip2region_jars"
require "java"

class LogStash::Filters::Ip2region < LogStash::Filters::Base
  config_name "ip2region"

  def self.javaClass() Java::org.logstashplugins.Ip2region.java_class; end
end
